menu:
  Home: /
  Archives: /archives

widgets:
- search

cover:
  enable: true
  url: fancybox/356317.jpg
   
excerpt_link: Read More

full_format: 'ddd, MMM D YYYY, h:mm:ss a'

addthis:
  enable: true
  pubid:
  facebook:
  twitter: true
  google:
  pinterest:

fancybox: true

google_analytics: UA-368771XX-X
rss:

comment_provider: duoshuo

# Duoshuo comment
duoshuo:
  short_name: your_id

social:
  github: https://github.com/ym2067
  weibo:
  google_plus: 

auto_change:
  enable: true
